Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)

# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**

In [1]:
import numpy as np

In [2]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
lst = [1,2,3,4,5]
arr = np.array(lst) 
print(arr) 

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
my_list = [[1,2,3],[4,5,6],[7,8,9]]
my_array = np.array(my_list)

print(my_array)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [31]:
# Write a NumPy function to create an array with random values of shape [3,4]


def create_random_array():
    return np.random.rand(3,4)

my_array = create_random_array()
print(my_array)    

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
def create_zero_array():
    return np.zeros((3,4))

my_array = create_zero_array()
print(my_array)


# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
def create_ones_array():
    return np.ones((3,4))

my_array = create_ones_array()
print(my_array)

[[0.84478623 0.01385769 0.42993796 0.78339669]
 [0.85128072 0.96709843 0.34880192 0.26883989]
 [0.85137161 0.09672078 0.9062792  0.34857227]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [5]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
def create_array_with_linspace(start, stop, num):
    return np.linspace(start, stop, num)

arr = create_array_with_linspace(0,1,10)
print(arr)
# Hint : Use np.arange or np.linspace

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

### Basic array operations
- algebraic operations 
- logical operations

In [32]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [33]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
c = a + b
print("Addition of a and b:",c)

c = a - b
print("Subtraction of a and b:",c)

c = a * b
print("Multiplication of a and b:",c)

c = a / b
print("Division of a and b:",c)

Addition of a and b: [[ 7 22 26]
 [99 40 82]
 [62 56 80]]
Subtraction of a and b: [[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
Multiplication of a and b: [[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
Division of a and b: [[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]

In [34]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
def sum_along_axis_0(a):
    return np.sum(a, axis=0)

result = sum_along_axis_0(a)
print(result)



# Write a NumPy function to get the sum of the array 'a' along axis=1 
def sum_along_axis(arr):
    return np.sum(arr, axis=1)

result = sum_along_axis(a)
print(result)

[ 6 17 14]
[10 13 14]

In [35]:
# Write a NumPy function to reverse the array 'a' 
def reverse_array(a):
    return np.flip(a)

reversed_a = reverse_array(a)
print(reversed_a)

# Write a NumPy function to reverse the array 'a' along axis=0
def reverse_along_axis_0(arr):
    return np.flip(arr, axis=0)

reversed_a = reverse_along_axis_0(a)
print(reversed_a)

# Write a NumPy function to reverse the array 'a' along axis=1
def reverse_array_along_axis_1(a):
    return np.flip(a, axis=1)

print("Origional array:\n",a)

reversed_array = reverse_array_along_axis_1(a)
print("Reversed array along axis=1:\n", reversed_array)

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
Origional array:
 [[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]
Reversed array along axis=1:
 [[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]

### Sorting and concatenation
- sort arrays
- join multiple arrays

In [36]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [37]:
# Write a NumPy function to sort the array 'a' 
def sort_array(a):
    sorted_a = np.sort(a, axis=0)
    return sorted_a
sorted_a = sort_array(a)
print(sorted_a)

# Write a NumPy function to sort the array 'a' along axis=0

sorted_array = np.sort(a, axis=0)
print(sorted_array)

# Write a NumPy function to sort the array 'a' along axis=1
def sort_array_along_axis_1(a):
    sorted_array = np.sort(a, axis=1)
    return sorted_array
sorted_array = sort_array_along_axis_1(a)
print(sorted_array)


# Write a NumPy function to sort the array 'a' in descending order along axis=0

def sort_array_descending(a):
     return np.sort(a, axis=0)[::-1]

sorted_a = sort_array_descending(a)
print(sorted_a)

[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]

In [38]:
# Write a NumPy function to argsort the array along axis=0
def argsort_along_axis(array):
    return np.argsort(array, axis=0)

arr = np.array([[-4,6,8],[9,3,1],[1,8,5]])

argsort_along_axis(arr)


# Write a NumPy function to argsort the array along axis=1

sorted_indices = np.argsort(a, axis=1)

print(sorted_indices)

[[0 1 2]
 [2 1 0]
 [0 2 1]]

In [39]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'

def concatenate_arrays(a,b):
    return np.concatenate((a,b), axis=0)
c = concatenate_arrays(a,b)
print(c)


# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0

def concat_arrays(a,b):
    return np.concatenate((a,b),axis=0)

concatenated_array = concat_arrays(a,b)
print(concatenated_array)




# Note: You can do the same function using stacking, discover and try that :)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [40]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [43]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)

# Write a NumPy function to get the Shape of the array 
print(np.shape(a))

# Write a NumPy function to get the Size of the array
print(a.size)

2
(3, 3)
9

In [44]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
a_reshaped = np.reshape(a, (1,9))
print(a_reshaped)

[[4 6 8 9 3 1 1 8 5]]

In [45]:
# Write a NumPy function to add a new axis to the array 'a' 

arr1 = a[np.newaxis, :]
arr2 = np.expand_dims(a, axis=0)
print(arr1.shape)
print(arr2.shape)

# Note : Show atleast two different ways of doing this

(1, 3, 3)
(1, 3, 3)

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [81]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [82]:
 # Write a NumPy function to index and slice NumPy arrays similar to Python lists
def numpy_indexing(a, indices):

    if isinstance(indices, int):
      return a[indices]
    elif isinstance(indices, tuple):
      return a[indices]
    elif isinstance(indices, range):
      return a[indices]
    else:
      raise ValueError("Invalid index type")

print(numpy_indexing(a,1))

print(numpy_indexing(a,(2,1)))

print(numpy_indexing(a,range(1,3)))



# Show all three - indexing by a integer, indexing by a tuple, using range

[0 3 1]
8
[[0 3 1]
 [1 8 5]]

In [83]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
def check(a, y):
    x = a>y
    return a[x]
req = check(a, 4)
print(req)

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def doublecheck(a):
    x = (a>4)&(a%2 == 0)
    return a[x]
req = doublecheck(a)
print(req)

[6 8 5]
[6 8]

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [84]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [85]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def inc_arr(a):
    b = a.copy()
    b += 1
    return b
inc_a = inc_arr(a)
print(inc_a)

[[5 7 1]
 [1 4 2]
 [2 9 6]]

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.

#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [86]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [87]:
import pandas as pd

In [88]:
# Write a Pandas function to drop rows that contain a missing value. 
import pandas as pd
def droprows(df):
       df_dropped = df.dropna()
       return df_dropped
df=pd.DataFrame(iris_2d)
df_dropped = droprows(df)
print(df_dropped)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [89]:
# Write a Pandas function to drop rows that contain a missing value. 
import pandas as pd
def correlation(df):
  x = df.iloc[:, 0:2]
  cor=x.corr()
  return cor
  df=pd.DataFrame(iris_2d)
cor=correlation(df)
print(cor)

          0         1
0  1.000000 -0.109369
1 -0.109369  1.000000

In [92]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
df = pd.DataFrame(iris_2d)
mean,median,std_dev = stats(df, 3)
print(df.mean()[2])
print(df.median()[2])
print(df.std()[2])

3.7586666666666693
4.35
1.7644204199522626

In [95]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
import math as mt
ar = []
for i in range(0, len(df)):
    ar.append((mt.pi * df.loc[i][2] * (df.loc[i][0])**2)/float(3))
df['Volume'] = ar
print(df)

       0    1    2    3      Volume
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [60]:
x = np.arange(4, dtype=np.int64)
ones_array = np.ones_like(x)

print(ones_array)

[1 1 1 1]

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [62]:
x= np.arange(1,10)
split_arrays = np.split(x, [4,6])
print(split_arrays)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [63]:
np.random.seed(42)
arr=np.random.rand(2,5)*10
print("maximum values of array along axis=1:", np.max(arr, axis=1))
print("minimum values of array along axis=1:", np.min(arr, axis=1))
print("indices of max values along axis=1:", np.argmax(arr, axis=1))
print("indices of min values along axis=1:", np.argmin(arr, axis=1))

maximum values of array along axis=1: [9.50714306 8.66176146]
minimum values of array along axis=1: [1.5601864  0.58083612]
indices of max values along axis=1: [1 2]
indices of min values along axis=1: [4 1]

### Pandas

Run the following load command and solve the following questions

In [64]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [66]:
def count_unique(data):
  unique = data.nunique()
  return unique
data = pd.DataFrame(iris)
x = count_unique(data)
print(x)

0    35
1    23
2    43
3    22
4     3
dtype: int64

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [67]:
def binpetal_length(data):
  data['petal_length_bin']=pd.cut(data['petallength'], bins=[0,3,5, float('inf')], labels=['small','medium','large'], right=False)
  return data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = pd.read_csv(url, header=None, names=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])
iris_2d_binned = binpetal_length(iris_2d)
print(iris_2d_binned)

     sepallength  sepalwidth  petallength  petalwidth         species
0            5.1         3.5          1.4         0.2     Iris-setosa  \
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

    petal_length_bin
0              small
1              small
2              small
3              small
4              small
..               ...
145            large
146            large
147            large
148            large
149            large

[150 rows x 6 columns]

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [68]:
def frequent_petal_length(url):
    iris = pd.read_csv(url, header=None, names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'))
    most_frequent_value = iris['petallength'].mode().values[0]
    return most_frequent_value
    url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
most_frequent_value = frequent_petal_length(url)
print("Most frequent value of petal length:", most_frequent_value)

Most frequent value of petal length: 1.5